/**
 * Error Codes Constants
 * Centralized error codes for consistent error handling
 */

export const ErrorCodes = {
  // Authentication Errors (1000-1099)
  AUTH_MISSING_TOKEN: 'AUTH_1001',
  AUTH_INVALID_TOKEN: 'AUTH_1002',
  AUTH_EXPIRED_TOKEN: 'AUTH_1003',
  AUTH_USER_NOT_FOUND: 'AUTH_1004',
  AUTH_INVALID_CREDENTIALS: 'AUTH_1005',
  AUTH_EMAIL_ALREADY_EXISTS: 'AUTH_1006',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_1007',

  // Validation Errors (2000-2099)
  VALIDATION_REQUIRED_FIELD: 'VALIDATION_2001',
  VALIDATION_INVALID_FORMAT: 'VALIDATION_2002',
  VALIDATION_OUT_OF_RANGE: 'VALIDATION_2003',
  VALIDATION_INVALID_EMAIL: 'VALIDATION_2004',
  VALIDATION_PASSWORD_TOO_SHORT: 'VALIDATION_2005',

  // Resource Errors (3000-3099)
  RESOURCE_NOT_FOUND: 'RESOURCE_3001',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_3002',
  RESOURCE_CONFLICT: 'RESOURCE_3003',
  RESOURCE_FORBIDDEN: 'RESOURCE_3004',

  // Appointment Errors (4000-4099)
  APPOINTMENT_SLOT_NOT_AVAILABLE: 'APPOINTMENT_4001',
  APPOINTMENT_INVALID_STATUS: 'APPOINTMENT_4002',
  APPOINTMENT_CANNOT_CANCEL: 'APPOINTMENT_4003',
  APPOINTMENT_ALREADY_CONFIRMED: 'APPOINTMENT_4004',

  // Payment Errors (5000-5099)
  PAYMENT_INSUFFICIENT_FUNDS: 'PAYMENT_5001',
  PAYMENT_STRIPE_ERROR: 'PAYMENT_5002',
  PAYMENT_INVALID_AMOUNT: 'PAYMENT_5003',
  PAYMENT_ALREADY_PROCESSED: 'PAYMENT_5004',
  PAYMENT_REFUND_FAILED: 'PAYMENT_5005',

  // Subscription Errors (6000-6099)
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_6001',
  SUBSCRIPTION_LIMIT_REACHED: 'SUBSCRIPTION_6002',
  SUBSCRIPTION_PAYMENT_FAILED: 'SUBSCRIPTION_6003',
  SUBSCRIPTION_NOT_ACTIVE: 'SUBSCRIPTION_6004',

  // Business Logic Errors (7000-7099)
  BUSINESS_INVALID_OPERATION: 'BUSINESS_7001',
  BUSINESS_LIMIT_EXCEEDED: 'BUSINESS_7002',
  BUSINESS_PRECONDITION_FAILED: 'BUSINESS_7003',

  // Server Errors (9000-9099)
  SERVER_INTERNAL_ERROR: 'SERVER_9001',
  SERVER_DATABASE_ERROR: 'SERVER_9002',
  SERVER_EXTERNAL_SERVICE_ERROR: 'SERVER_9003'
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];

